Repository TeamWAGMI/LetsSeoul, pull requests merged in 2022-09, with the labels that each got.

#44 PR: feat/be/au-0001 to be
  .github/workflows/be-cd.yml
  .github/workflows/cicd.yml
  backend/README.md
  backend/letsSeoulApp/.gitignore
  backend/letsSeoulApp/.gradle/7.5/checksums/checksums.lock
  backend/letsSeoulApp/.gradle/7.5/checksums/md5-checksums.bin
  backend/letsSeoulApp/.gradle/7.5/checksums/sha1-checksums.bin
  backend/letsSeoulApp/.gradle/7.5/dependencies-accessors/dependencies-accessors.lock
  backend/letsSeoulApp/.gradle/7.5/executionHistory/executionHistory.lock
  backend/letsSeoulApp/.gradle/7.5/fileHashes/fileHashes.lock
  backend/letsSeoulApp/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  backend/letsSeoulApp/.gradle/buildOutputCleanup/cache.properties
  backend/letsSeoulApp/.idea/.gitignore
  backend/letsSeoulApp/.idea/.name
  backend/letsSeoulApp/.idea/gradle.xml
  backend/letsSeoulApp/.idea/jarRepositories.xml
  backend/letsSeoulApp/.idea/jpa-buddy.xml
  backend/letsSeoulApp/.idea/misc.xml
  backend/letsSeoulApp/.idea/sonarlint/issuestore/1/4/1406c0bdd9807d06097b2aa19215195a64e16429
  backend/letsSeoulApp/.idea/sonarlint/issuestore/a/5/a5cc2925ca8258af241be7e5b0381edf30266302
  backend/letsSeoulApp/.idea/sonarlint/issuestore/f/0/f07866736216be0ee2aba49e392191aeae700a35
  backend/letsSeoulApp/.idea/sonarlint/issuestore/index.pb
  backend/letsSeoulApp/.idea/tmp-repo-mainproject.iml
  backend/letsSeoulApp/.idea/uiDesigner.xml
  backend/letsSeoulApp/.idea/vcs.xml
  backend/letsSeoulApp/build.gradle
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/JpaConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/WebConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationFailureHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationSuccessHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2UserService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/LoginUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/LoginUserArgumentResolver.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/SecurityConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/dto/OAuthAttributes.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/dto/SessionUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/OAuth2Controller.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/util/CookieUtil.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/util/KakaoRestApiHelper.java
  backend/letsSeoulApp/src/main/resources/application-oauth.yml
  backend/letsSeoulApp/src/main/resources/application.yml
Labels: aka-nick, feat/be

#63 Feat/be/th-0003-st to BE
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationSuccessHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Store.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Theme.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java
Labels: aka-nick, feat/be

#68 FEAT: 테마 검색 스텁, 테마찜 등록 스텁
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java
Labels: aka-nick, feat/be

#75 FEAT: 테마 리뷰 등록 스텁
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java
Labels: aka-nick, feat/be

#77 PR: Themes API 스텁작업 완료
  .github/workflows/be-cd.yml
  .github/workflows/cicd.yml
  .github/workflows/fe-cd.yml
  backend/letsSeoulApp/.gitignore
  backend/letsSeoulApp/.gitmessage.txt
  backend/letsSeoulApp/build.gradle
  backend/letsSeoulApp/gradle/wrapper/gradle-wrapper.jar
  backend/letsSeoulApp/gradle/wrapper/gradle-wrapper.properties
  backend/letsSeoulApp/gradlew
  backend/letsSeoulApp/gradlew.bat
  backend/letsSeoulApp/settings.gradle
  backend/letsSeoulApp/src/docs/asciidoc/index.adoc
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/LetsSeoulAppApplication.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/CorsConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/JpaConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/SecurityConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/WebConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/audit/Auditable.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationFailureHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationSuccessHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2UserService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/LoginUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/LoginUserArgumentResolver.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/dto/OAuthAttributes.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/dto/SessionUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/OAuth2Controller.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Store.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Theme.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/ThemeStore.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/MultiResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/PageInfo.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/SingleListResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/UserDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/util/CookieUtil.java
  backend/letsSeoulApp/src/test/java/com/letsseoul/letsSeoulApp/LetsSeoulAppApplicationTests.java
Labels: aka-nick, feat/be

#89 FEAT: 특정 유저 리뷰 장소조회 ,특정 유저 찜 장소 조회
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/LocationController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/LocationDto.java
Labels: feat/be, MJS

#90 FEAT: 유저 이모지 변경, 유저정보변경,유저정보 조회
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/UserDto.java
Labels: feat/be, MJS

#91 FEAT: 가게정보조회,가게찜 여부조회,가게찜등록,가게찜 취소
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/StoreDto.java
Labels: feat/be, MJS

#92 PR: follow 스텁 작업
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/FollowDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java
Labels: aka-nick, feat/be

#93 PR: Stub code 작성 완료로 인한 be to dev PR
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/LocationController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/FollowDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/LocationDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/StoreDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/UserDto.java
Labels: aka-nick, feat/be, MJS

#94 PR: FE to DEV
  frontend/public/images/back.svg
  frontend/public/images/hamburger.svg
  frontend/public/images/kakaotalk.svg
  frontend/public/images/logo.svg
  frontend/public/images/refresh.svg
  frontend/public/images/search.svg
  frontend/src/Router.js
  frontend/src/components/Button.js
  frontend/src/components/Card.js
  frontend/src/components/Footer.js
  frontend/src/components/Header.js
  frontend/src/components/ImageUpload.js
  frontend/src/components/Input.js
  frontend/src/components/Modal.js
  frontend/src/components/Review.js
  frontend/src/components/Score.js
  frontend/src/components/SearchBar.js
  frontend/src/components/Tag.js
  frontend/src/components/Textarea.js
  frontend/src/index.css
  frontend/src/libraries/utils.js
  frontend/src/pages/Main.js
  frontend/src/pages/Request.js
  frontend/src/pages/RequestForm.js
  frontend/src/pages/Review.js
  frontend/src/pages/ReviewForm.js
  frontend/src/pages/Search.js
  frontend/src/pages/StoreInfo.js
  frontend/src/pages/UserInfo.js
  frontend/src/static/dummyData.js
  frontend/src/styles/props.js
  frontend/tailwind.config.js
Labels: SEO, aka-nick, JungYoon, feat/fe, feat/be, MJS

#139 Feat/be/fo 0001
  .github/workflows/be-cd.yml
  .github/workflows/cicd.yml
  .github/workflows/fe-cd.yml
  backend/letsSeoulApp/build.gradle
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/dto/SessionUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/FollowUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Theme.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/FollowDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/MultiResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/PageInfo.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/FollowService.java
Labels: feat/be, MJS

#140 PR: feat/be/us-0003 to be
  backend/letsSeoulApp/build.gradle
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/SecurityConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationSuccessHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/FollowUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Theme.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/MultiResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/PageInfo.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/UserDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/follow/FollowDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/follow/FollowerResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/FollowService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/util/EmojiUtil.java
Labels: aka-nick, feat/be

#141 PR: tmp to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/FollowUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/HotUser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/MultiResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/follow/FollowDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/FollowService.java
Labels: feat/be
