Repository TeamWAGMI/LetsSeoul, pull requests merged in 2022-10, with the labels that each got.

#145 PR: feat/be/cu-0001 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/OAuth2Controller.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Hottheme.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Hotuser.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Review.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Store.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/ThemeStore.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/follow/FollowDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/PopularThemeListResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/RecommendedThemeListResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/user/CuratorListResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/user/UserDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/HotthemeRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/HotuserRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ReviewRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/StoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeStoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java
Labels: aka-nick, feat/be

#146 PR: feat/be/th-0011 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/FollowTheme.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/user/UserDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowThemeRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/UserRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java
Labels: feat/be

#171 PR: fix to feat
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Review.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowStoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ReviewRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/StoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java
Labels: fix, aka-nick

#173 PR: TH-0009 QueryDsL 구현
  backend/letsSeoulApp/build.gradle
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/JpaConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2UserService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Store.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Theme.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/ThemeTag.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeCustomRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeCustomRepositoryImpl.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
Labels: feat/be, MJS

#174 PR: feat/be/st-0001 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/LocationController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/FollowStore.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Review.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/StoreDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/location/DibsPlaceResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/location/ReviewPlaceResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowStoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ReviewRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/StoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/LocationService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/StoreService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/UserService.java
Labels: aka-nick, feat/be

#175 PR: feat/bet/th-0003 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Review.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/Store.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/ThemeTag.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/store/StoreDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/store/StoreThemeResponse.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/store/StoreThemeReviewResponse.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeMapListResponseDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ReviewRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeStoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/StoreService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
Labels: feat/be, MJS

#181 PR: fix/be/testfix-0001 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/LocationController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/OAuth2Controller.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/LocationDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/follow/FollowDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/user/UserDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowStoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeStoreRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/FollowService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
Labels: aka-nick, feat/be, MJS

#189 PR: 개발환경 변경에 따른 수정 코드 머지
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/SecurityConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationSuccessHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2UserService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/domain/User.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/util/EmojiUtil.java
Labels: aka-nick, feat/be, MJS

#206 PR: au-0002 코드리뷰 반영 리팩토링
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/SecurityConfig.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationFailureHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2AuthenticationSuccessHandler.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/CustomOAuth2UserService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/config/auth/LoginUserArgumentResolver.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/OAuth2Controller.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/util/EmojiUtil.java
Labels: aka-nick, refactor

#210 PR: HOTFIX: th-0004-2
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
Labels: fix, aka-nick

#214 PR : fix/be/th-0014 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/dto/theme/ThemeDto.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/FollowService.java
Labels: fix

#217 PR: fix/be/th-0008 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/UserController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/StoreService.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
Labels: fix, MJS

#232 PR: fix/be/th-0014 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/FollowController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowThemeRepository.java
Labels: bug, fix, MJS

#235 PR fix/be/th-0005 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/FollowRepository.java
Labels: bug, fix, MJS

#237 PR: fix/be/th-0009 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/ThemeController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/repository/ThemeCustomRepositoryImpl.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/ThemeService.java
Labels: fix, MJS

#249 PR : fix/be/th-0007 to be
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/controller/StoreController.java
  backend/letsSeoulApp/src/main/java/com/letsseoul/letsSeoulApp/service/StoreService.java
Labels: fix, aka-nick, MJS
